name: Deploy and Migrate Django

on:
  push:
    branches:
      - main  # or the branch you are deploying

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # or your project's Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Migrations
      run: |
        python manage.py migrate

    - name: Deploy to Render
      run: |
        # Add your deployment steps here
        # Example: git push to Render
        git push render main
